# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d00852f6d44e8ce8dd6a3ecb3e4be32574c32e54ebdd0821f18cbdf3e24a47ec620620a7fb16c711682efcbc255ec6d5ae98cedce45eb7d416c4369f5a12c39a

test:
  secret_key_base: 0a38ac2533639babfcf5e37221c0f36443e9dce342d67f079f55654e28efccf829d3dd338c79e9936435ef207bee98ef2c68bb6174254ce98c7ce001b16d74ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
